# Generated by Django 2.1.5 on 2019-01-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190130_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
